# Generated by Django 3.2.9 on 2022-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.AddField(
            model_name='petition',
            name='status',
            field=models.CharField(default='Збір підписів', max_length=100),
        ),
    ]
