# Generated by Django 3.2.9 on 2022-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220808_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='topic', to='base.Topic'),
        ),
    ]
