# Generated by Django 3.2.9 on 2022-08-08 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_petition_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='author',
        ),
        migrations.AddField(
            model_name='petition',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='petition',
            name='topic',
        ),
        migrations.AddField(
            model_name='petition',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.topic'),
        ),
    ]
